navbar:
  - Index: index.html
  - Quick Start: quick-start.html
  - Docs: docs.html
  - Dev Guide: developer-guide.html
  - Tags: tags.html
  - Notes: notes.html
  - Posts: posts.html
baseURL: https://anna-docs.netlify.app
siteTitle: "anna-docs"
siteScripts:
author: anna
themeURL: "/static/style.css"
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International."
